### ISSUE TITLE
各种bug，垃圾。浪费了我很多时间

### ISSUE THREAD

**Issue by xing9133** [junjunlab/scRNAtoolVis#15]

**Comment by junjunlab** [comment]
有问题就好好沟通解决, 骂人干啥?

**Comment by zjhcarbonic** [comment]
> 有问题就好好沟通解决, 骂人干啥?

这种就是典型的“小人”，作者辛苦开发软件免费供大家使用，他既然会注册github，有bug就提交就是了，上来就喷粪，破坏开源环境，真是一坨答辩，搁哪儿都让人恶心。

**Comment by onlyyouonlyyou** [comment]
> _No description provided._

这个沙雕，自己不贡献蛋糕，还吃奶骂娘，自己那么多B事，有本事你自己写个包出来啊？小垃圾

**Comment by xlucpu** [comment]
> _No description provided._

不刷牙的伸手党，哪个学校哪个老师教出来的奇葩。

**Comment by junjunlab** [comment]
> > 有问题就好好沟通解决, 骂人干啥?
> 
> 这种就是典型的“小人”，作者辛苦开发软件免费供大家使用，他既然会注册github，有bug就提交就是了，上来就喷粪，破坏开源环境，真是一坨答辩，搁哪儿都让人恶心。

没毛病,老铁

**Comment by junjunlab** [comment]
> 

他主页啥也没有

**Comment by junjunlab** [comment]
> > _No description provided._
> 
> 这个沙雕，自己不贡献蛋糕，还吃奶骂娘，自己那么多B事，有本事你自己写个包出来啊？小垃圾

他主页啥也没有

**Comment by junjunlab** [comment]
> > _No description provided._
> 
> 不刷牙的伸手党，哪个学校哪个老师教出来的奇葩。

给师兄点赞
