### ISSUE TITLE
Error in utils::download.file(url, path, method = method, quiet = quiet,  :    download from 'https://api.github.com/repos/junjunlab/scRNAtoolVis/tarball/HEAD' failed

### ISSUE THREAD

**Issue by hyq9588** [junjunlab/scRNAtoolVis#25]
devtools::install_github('junjunlab/scRNAtoolVis')
Using github PAT from envvar GITHUB_TOKEN
Downloading GitHub repo junjunlab/scRNAtoolVis@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/junjunlab/scRNAtoolVis/tarball/HEAD' failed.

I have a good Internet connection and can access github normally. How can I solve this problem?

**Comment by hyq9588** [comment]
The problem has been resolved.

**Comment by zhoududu1001** [comment]
> The problem has been resolved.

How did you solve it?thx
