### ISSUE TITLE
Ask for enhancement.

### ISSUE THREAD

**Issue by Knight1995** [junjunlab/scRNAtoolVis#6]
Dear Mr.JUN,what a wonderful function of jjDotPlot,i wanna use your code to repeat the blog,but there is an error.i google it,but didn't find the answer. The following is the running log:
1.jjDotPlot(object = scRNA,
               gene = unique(top10$gene),
               id = 'celltype',
               split.by = 'group',
               dot.col = color3,
               split.by.aesGroup = T,
               point.geom = F,
               tile.geom = T)
Erro：object 'pbmc' not found 
2. Are the image size parameters adjustable? I didn't find the relevant parameters, resulting in a large canvas but little change in the image.
Thanks.

**Comment by junjunlab** [comment]
Try re-install scRNAtoolVis. Besides you can set theme(aspect.ratio = yoursize) to change image size.

**Comment by Knight1995** [comment]
Thanks.Problem solved!
